name: Rust

on:
  push:
    branches: [ master ]
    tags:
      - "*"
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    # make sure all code has been formatted with rustfmt
    - run: rustup component add rustfmt
    - name: check rustfmt
      run: cargo fmt -- --check --color always
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
